<% project_name = 'expecting' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= expecting %>_development

test:
  <<: *default
  database: <%= expecting %>_test
